### PR TITLE
Fixed warnings "useNativeDriver was not specified"

### PR DESCRIPTION
**Pull request by brunobrante**
Fixed warning "useNativeDriver was not specified" and "Animated.event now requires a second argument for options"

### CODE REVIEW

**Comment by Pat-Gekoski** [comment]
when will this be published?

**Comment by leavitdav01** [comment]
Reiterating what Pat said, when's this going to get published?

**Comment by johannb75** [comment]
Does anyone have an idea when this is going to get published ??

**Comment by adamgajzlerowicz** [comment]
I don't think the maintainer is around :(

**Comment by maxs15** [comment]
Merging the PR, will try to spend a little more time keeping this plugin up to date, sorry guys.

**Pull request merged**
