### PR TITLE
Bug fixes from swiping 

### PR DESCRIPTION
**Pull request by TheNerdGuyLulu**
Fixes for:
Preventing swipe from getting stuck when swipeThreshold position not reached;
Set the state to the starting position of the modal, preventing animating from where the swipe stopped;
Remove event listener for back button when swipe to close

### CODE REVIEW

**Comment by maxs15** [comment]
Thanks @TheNerdGuyLulu

**Comment by jamesmsp89** [comment]
Thanks @TheNerdGuyLulu. 

@maxs15 when can I expect a new release with this fix in?

**Comment by maxs15** [comment]
I want to check everything, to be sure it doesn't introduce other bugs.
I'll do that this week-end.

**Comment by jamesmsp89** [comment]
Sounds great, thanks @maxs15 !

**Comment by maxs15** [comment]
Released in v2.0.0 !

**Pull request merged**
