### PR TITLE
improve component with listener on height change with entry="bottom" only

### PR DESCRIPTION
**Pull request by MassimoFortarezza**
Pr to enable the component to receive a new height while it is still mounted. Fixes also issue about flicker when in nativeDriver=true

### CODE REVIEW

**Comment by lorenzoangelini** [comment]
@maxs15 Hi Max could you marge this pr? For me is very useful

**Comment by mauroerta** [comment]
I tested this branch and it works fine! please merge 🙏🏻

**Comment by Blind12** [comment]
Any progress on this ? Tested and works well

**Comment by MassimoFortarezza** [comment]
We are currently using it in our app.  I don't think they will merge this
fork into official repo, since I got no update from official maintainer.
Feel free to use this, if it's stable for you too.
😀

Il gio 14 mag 2020, 09:31 Blind12 <notifications@github.com> ha scritto:

**Pull request closed without merging**
