### PR TITLE
Adding `swipeTarget` to limit swipe gesture to single component

### PR DESCRIPTION
**Pull request by gavinlynch**
I'm using this to limit the swipe gesture response only to a single component. This is useful for me because I have a ScrollView inside the Modal, and the position of the element that I would like to respond to the swipe changes, and I found it problematic to update the swipe area based on the Y value of my component on the page as it changes on scroll.

My scenario is a map at the top of a scroll view, and I really only want the entire modal to close when the user is swiping the map.

If there is a more idiomatic React way to target components, that input would be appreciated. New to react-native in general :)

### CODE REVIEW

**Comment by gavinlynch** [comment]
any thoughts on this?

**Comment by maxs15** [comment]
If I'm understanding property, let's say you have a arrow inside the modal.
You only want the modal to swipe when the user touch this arrow ? Is it right ?

**Comment by gavinlynch** [comment]
Hi @maxs15, yes exactly correct. Thanks for your reply, hope you're having a good weekend.

**Comment by maxs15** [comment]
Ok, we could have done cleaner by creating a sub-component I guess like that:
```
<Modalbox>
    <Modalbox.Toggle>
         <Icon name="map"/>
    </Modalbox.Toggle>
    {modalContent}
</Modalbox>
```
In the meantime let's merge your PR since it's a minor change, could you please commit an example as well ? (Example folder)
Thanks

**Pull request closed without merging**
