### PR TITLE
implement left and right

### LINKED ISSUE #86: Need 'left' and 'right' in entry props!
Anyway to use this as a Side Menu?
Like i could use 'left' or 'right' in 'entry' prop and bring git from the side?

### PR DESCRIPTION
**Pull request by macrozone**
fixes #86 

my linter accidentially replaced var with const. hope you don't mind... (const is anyway better to use)

I released it to test under `@panter/react-native-modalbox`

### CODE REVIEW

**Comment by theohdv** [comment]
Is it going to be merged soon? useful PR for me!

**Comment by macrozone** [comment]
@theohdv try installing `@panter/react-native-modalbox`

**Comment by theohdv** [comment]
Then you I just need to set entry attribute to 'right' for example?

```javascript
<Modal
  animationType={"slide"}
  visible={true}
  entry='right'/>
```

**Comment by kirushi** [comment]
looking forward to this addition!

**Comment by theohdv** [comment]
@kirushi check this lib [react-native-modal](https://github.com/react-native-community/react-native-modal) (as this one seems to not be maintained anymore).

**Pull request closed without merging**
