### PR TITLE
Only recalculate layout if dimensions change

### PR DESCRIPTION
**Pull request by edmofro**
Optimisation, fixing some laggy behaviour

### CODE REVIEW

**Comment by edmofro** [comment]
Here's another one for you @maxs15 :-)

**Comment by edmofro** [comment]
Do you think this could be merged @maxs15?

**Comment by edmofro** [comment]
Also removed a separate optimisation to fix #82 @maxs15

**Comment by edmofro** [comment]
P.S. I finish my current job in two days, so it would be great to get this merged before that!

**Comment by maxs15** [comment]
Thanks @edmofro, going to merge it

**Pull request merged**
