### PR TITLE
Add coverScreen prop to fit parent components

### PR DESCRIPTION
**Pull request by prtkkmrsngh**

### CODE REVIEW

**Comment by maxs15** [comment]
Thanks @prtkkmrsngh 👍 
Going to merge it

**Comment by prtkkmrsngh** [comment]
Cool 😎

**Comment by fungilation** [comment]
Should document its use on README

**Comment by wolfg1969** [comment]
This won't cover the status bar on Android even if use <StatusBar hidden/> 
see https://github.com/facebook/react-native/issues/7474

**Comment by prtkkmrsngh** [comment]
@wolfg1969 Yes this won't. I created this PR to just cover parent component. For example in case of sliding tab view.

**Pull request merged**
