### PR TITLE
Replaced React.createClass with createReactClass

### PR DESCRIPTION
**Pull request by iRoachie**
React.createClass was deprecated in react 15.5 and now shows an error in the latest react native projects. This PR replaces React.createClass with the drop-in replacement from facebook create-react-class

### CODE REVIEW

**Comment by fungilation** [comment]
I confirm the warning in console:
```
  | reactConsoleErrorHandler | @ | ExceptionsManager.js:71
-- | -- | -- | --
  | printWarning | @ | warning.js:36
  | warning | @ | warning.js:60
  | get | @ | react.development.js:2125
  | (anonymous) | @ | index.js:44    <-- <project>/node_modules/react-native-modalbox/index.js
  | loadModuleImplementation | @ | require.js:174
  | guardedLoadModule | @ | require.js:126
  | _require | @ | require.js:110
  | (anonymous) | @ | components.js:32
  | loadModuleImplementation | @ | require.js:174
  | guardedLoadModule | @ | require.js:126
  | _require | @ | require.js:110
  | (anonymous) | @ | index.ios.js:86
  | loadModuleImplementation | @ | require.js:174
  | guardedLoadModule | @ | require.js:119
  | _require | @ | require.js:110
  | (anonymous) | @ | redux-logger.js:1
  | executeApplicationScript | @ | debuggerWorker.js:40
  | (anonymous) | @ | debuggerWorker.js:65
```

Thanks for the PR! NPM bump soon?

**Comment by iRoachie** [comment]
@fungilation Unfortunately would have to wait till he decides to merge

**Comment by maxs15** [comment]
Merging the PR ! Thanks @iRoachie

**Comment by iRoachie** [comment]
@maxs15 Shocked me man! That was fast

**Pull request merged**
