### PR TITLE
Fix for Modal scrolling out of bottom while keyboard hide performed in iOS

### PR DESCRIPTION
**Pull request by xeric**
This is a fix for resolving keyboard hide performed while editing content in Modal, in iOS, keyboardHide and keyBoardChange triggered both, the calculation of keyboard height in keyboardChange action gets a negative value which make the Modal scroll out of screen bottom.

### CODE REVIEW

**Comment by harry503** [comment]
+1 Works Great! Thank you

**Comment by ManigandanRaamanathan** [comment]
This issue happens in android. Please provide a fix for android.

**Comment by ManigandanRaamanathan** [comment]
use this fix in index.js:-
keyboardOffset: this.props.position === 'top' || keyboardHeight > 0 ? keyboardHeight : 0

**Comment by AxayDixit** [comment]
@maxs15 Hello, I've been facing this issue on iOS where the  modal scroll down when the opened keyboard is closed inside it. How can I use your solution here?

**Pull request closed without merging**
