### PR TITLE
Use prop-types library as React.PropTypes is deprecated

### PR DESCRIPTION
**Pull request by edmofro**
This is a required change for anyone using react version 16 or higher

It does require that users have the prop-types package installed. At the moment you don't have any dependency management in the package.json, but you might want to add prop-types as either a dependency or a peerDependency

### CODE REVIEW

**Comment by edmofro** [comment]
Just added another commit (454aea7) which also fixes a bug since updating to react native 0.46. 

I have a modal that just appears in the lower quarter of the screen, but while open it was blocking touches to the rest of the screen.

**Comment by edmofro** [comment]
@maxs15 Would be great if you can merge this, as react-native-modalbox is unusable with the latest react-native stack while it uses React.PropTypes

**Comment by maxs15** [comment]
Thanks @edmofro, going to merge it !

**Comment by edmofro** [comment]
Cheers @maxs15

**Pull request merged**
